title: "What Do Developers Really Say About Their Skills and Careers?"
description: "Data analysis & ML insights from developer survey data"
markdown: kramdown
highlighter: rouge
baseurl: "/stackoverflow-survey-2025"
permalink: /:year/:month/:day/:title/
